### ISSUE TITLE
Bad path for Resources

### ISSUE THREAD

**Issue by mstechly** [CodieKev/QGames#2]
Instead of having path to resources specified as:
`H = pygame.image.load(r'Resource\H.jpg')`
I suggest doing:
`H = pygame.image.load(os.path('Resource', 'H.jpg'))`

This will work on any environemnt.

Also, the way it's currently set up doesn't work if you start jupyter notebook from the top directory (not sure if there's an easy way to fix that though).

**Comment by CodieKev** [comment]
I have updated the image loading codes as per your suggestion.
I ran the jupyter notebook as restart and run all multiples time and it workes for me. I have asked one of my friends to check on his pc for the error. I would try to clear those errors asap.
I'm all new to these things and honestly, it never came to my mind that environmental change would cause an error.
Thank You for pointing it out. I would remember this in all my projects onwards.

**Comment by CodieKev** [comment]
The error came because of the use of MCX Gate. 
In Qiskit 0.14.2 if mcx doesn't have any elements in the control argument then it will put an X Gate on the target qubit.
This feature is removed in Qiskit 0.16.4.
The new code has been made compatible with Qiskit 0.16.4 and will run on the previous version 0.14.2 as well.
Thank You.

**Comment by CodieKev** [comment]
Sorry, I pressed close with a comment instead of a comment.
